<?php

use Drupal\user\UserInterface;

/**
 * Implements hook_user_view().
 */
function killbill_user_view(array &$build, UserInterface $account, $view_mode, $langcode) {
  if (!$account->id() || !\Drupal::currentUser()->hasPermission('administer killbill')) {
    return;
  }
  if (!($killbill_account = Drupal\killbill\KillbillHelpers::retrieveAccount($account))) {
    return;
  }

  $account->content['killbill_account'] = array(
    '#type' => 'user_profile_category',
    '#title' => t('Killbill information'),
    '#weight' => 0,
  );

  if (empty($killbill_account->company)) {
    $account_holder = t('@name', array('@name' => $killbill_account->name));
  }
  else {
    $account_holder = t('@name, @company', array('@name' => $killbill_account->name, '@company' => $killbill_account->company));
  }

  $account->content['killbill_account']['account_holder'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Account holder'),
    '#markup' => $account_holder,
  );

  $account->content['killbill_account']['account_email'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Account e-mail address'),
    '#markup' => \Drupal\Component\Utility\SafeMarkup::checkPlain($killbill_account->email),
  );

  $account->content['killbill_account']['account_currency'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Account currency'),
    '#markup' => \Drupal\Component\Utility\SafeMarkup::checkPlain($killbill_account->currency),
  );

  $account->content['killbill_account']['account_timeZone'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Account time zone'),
    '#markup' => \Drupal\Component\Utility\SafeMarkup::checkPlain($killbill_account->timeZone),
  );

  $account->content['killbill_account']['account_kbid'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Killbill account id'),
    '#markup' => \Drupal\Component\Utility\SafeMarkup::checkPlain($killbill_account->accountId),
  );
}

/**
 * Implements hook_user_insert().
 */
function killbill_user_insert(UserInterface $account) {
  if (!Drupal\killbill\KillbillHelpers::createAccount($account)) {
    $message = t('Billing account was not created.');
    drupal_set_message($message, 'error');
    \Drupal::logger('killbill')->error($message);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function killbill_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  $form['killbill_account'] = array(
    '#type' => 'details',
    '#title' => t('KillBill settings (optional)'),
    '#description' => t('Optional settings for KillBill account'),
    '#open' => TRUE,
    '#tree' => TRUE,
    '#weight' => 10,
  );

  $form['killbill_account']['killbill_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
  );

  $form['killbill_account']['killbill_address1'] = array(
    '#type' => 'textfield',
    '#title' => t('Address 1'),
  );

  $form['killbill_account']['killbill_address2'] = array(
    '#type' => 'textfield',
    '#title' => t('Address 2'),
  );

  $form['killbill_account']['killbill_company_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Company name'),
  );

  $form['killbill_account']['killbill_city'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
  );

  $form['killbill_account']['killbill_state_or_province'] = array(
    '#type' => 'textfield',
    '#title' => t('State or province'),
  );

  $form['killbill_account']['killbill_country'] = array(
    '#type' => 'textfield',
    '#title' => t('Country'),
  );

  $form['killbill_account']['killbill_postal_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Postal code'),
  );

  $form['killbill_account']['killbill_phone'] = array(
    '#type' => 'tel',
    '#title' => t('Phone'),
  );

  $form['actions']['submit']['#submit'][] = '_killbill_form_user_register_form_submit';
}

/**
 * On submit process data.
 * @param array $form
 * @param FormStateInterface $form_state
 */
function _killbill_form_user_register_form_submit(array &$form, Drupal\Core\Form\FormStateInterface $form_state) {
  /* @var $account Drupal\user\Entity\User */
  $account = $form_state->getFormObject()->getEntity();
  Drupal\killbill\KillbillHelpers::updateAccount($account, array(
    'name' => $form_state->getValue('killbill_name') . ' | ' . $account->getUsername(),
    'address1' => $form_state->getValue('killbill_address1'),
    'address2' => $form_state->getValue('killbill_address2'),
    'company_name' => $form_state->getValue('killbill_company_name'),
    'city' => $form_state->getValue('killbill_city'),
    'state_or_province' => $form_state->getValue('killbill_state_or_province'),
    'country' => $form_state->getValue('killbill_country'),
    'postal_code' => $form_state->getValue('killbill_postal_code'),
    'phone' => $form_state->getValue('killbill_phone'),
  ));
}
