<?php

use Drupal\killbill\KillbillHelpers;

/**
 * Implements hook_user_view().
 */
function killbill_user_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if (!$entity->id() || !\Drupal::currentUser()->hasPermission('administer killbill')) {
    return;
  }
  $killbillHelpers = new KillbillHelpers();
  if (!($killbill_account = $killbillHelpers->retrieveAccount($entity))) {
    return;
  }

//  dvm($build['summary']);



  $build['killbill_account'] = array(
    '#type' => 'fieldset',
    '#title' => t('Killbill information'),
    '#weight' => 0,
  );

  if (empty($killbill_account->company)) {
    $account_holder = t('@name', array('@name' => $killbill_account->name));
  }
  else {
    $account_holder = t('@name, @company', array('@name' => $killbill_account->name, '@company' => $killbill_account->company));
  }

  $build['killbill_account']['account_holder'] = array(
    '#type' => 'item',
    '#title' => t('Account holder'),
    '#markup' => $account_holder,
  );

  $build['killbill_account']['account_email'] = array(
    '#type' => 'item',
    '#title' => t('Account e-mail address'),
    '#markup' => \Drupal\Component\Utility\SafeMarkup::checkPlain($killbill_account->email),
  );

  $build['killbill_account']['account_currency'] = array(
    '#type' => 'item',
    '#title' => t('Account currency'),
    '#markup' => \Drupal\Component\Utility\SafeMarkup::checkPlain($killbill_account->currency),
  );

  $build['killbill_account']['account_timeZone'] = array(
    '#type' => 'item',
    '#title' => t('Account time zone'),
    '#markup' => \Drupal\Component\Utility\SafeMarkup::checkPlain($killbill_account->timeZone),
  );

  $build['killbill_account']['account_kbid'] = array(
    '#type' => 'item',
    '#title' => t('Killbill account id'),
    '#markup' => \Drupal\Component\Utility\SafeMarkup::checkPlain($killbill_account->accountId),
  );
}

/**
 * Implements hook_user_insert().
 */
function killbill_user_insert(\Drupal\user\Entity\User $account) {
  $killbillHelpers = new KillbillHelpers();
  if ($killbillHelpers->createAccount($account)) {
    $message = t('Billing account was created.');
    drupal_set_message($message, 'status');
    \Drupal::logger('killbill')->notice($message);
  }
  else {
    $message = t('Billing account was not created.');
    drupal_set_message($message, 'error');
    \Drupal::logger('killbill')->error($message);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function killbill_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  $form['killbill_account'] = array(
    '#type' => 'details',
    '#title' => t('KillBill settings (optional)'),
    '#description' => t('Optional settings for KillBill account'),
    '#open' => TRUE,
    '#tree' => TRUE,
    '#weight' => 10,
  );

  $form['killbill_account']['killbill_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
  );

  $form['killbill_account']['killbill_address1'] = array(
    '#type' => 'textfield',
    '#title' => t('Address 1'),
  );

  $form['killbill_account']['killbill_address2'] = array(
    '#type' => 'textfield',
    '#title' => t('Address 2'),
  );

  $form['killbill_account']['killbill_company_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Company name'),
  );

  $form['killbill_account']['killbill_city'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
  );

  $form['killbill_account']['killbill_state_or_province'] = array(
    '#type' => 'textfield',
    '#title' => t('State or province'),
  );

  $form['killbill_account']['killbill_country'] = array(
    '#type' => 'textfield',
    '#title' => t('Country'),
  );

  $form['killbill_account']['killbill_postal_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Postal code'),
  );

  $form['killbill_account']['killbill_phone'] = array(
    '#type' => 'tel',
    '#title' => t('Phone'),
  );

  $form['actions']['submit']['#submit'][] = '_killbill_form_user_register_form_submit';
}

/**
 * On submit process data.
 * @param array $form
 * @param FormStateInterface $form_state
 */
function _killbill_form_user_register_form_submit(array &$form, Drupal\Core\Form\FormStateInterface $form_state) {
  /* @var $account \Drupal\user\Entity\User */
  $user = $form_state->getFormObject()->getEntity();
  $killbill_account = $form_state->getValue('killbill_account');
  $killbillHelpers = new KillbillHelpers();
  $killbillHelpers->updateAccount($user, array(
    'name' => $killbill_account['killbill_name'] . ' | ' . $user->getUsername(),
    'firstNameLength' => strlen($killbill_account['killbill_name'] . ' | ' . $user->getUsername()),
    'address1' => $killbill_account['killbill_address1'],
    'address2' => $killbill_account['killbill_address2'],
    'company_name' => $killbill_account['killbill_company_name'],
    'city' => $killbill_account['killbill_city'],
    'state_or_province' => $killbill_account['killbill_state_or_province'],
    'country' => $killbill_account['killbill_country'],
    'postal_code' => $killbill_account['killbill_postal_code'],
    'phone' => $killbill_account['killbill_phone'],
  ));
}
