<?php

/**
 * Implements hook_requirements().
 */
function killbill_requirements($phase) {
  $requirements = [];
  if ($phase == 'install') {
    require_once DRUPAL_ROOT . '/vendor/killbill/killbill-client-php/lib/killbill.php';
    if (!class_exists('\Killbill_Account')) {
      $requirements['killbill_library'] = [
        'description' => t('KillBill requires the killbill/killbill-client-php library.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}
