<?php

/**
 * Implements hook_user_view().
 */
function killbill_user_view(array &$build, \Drupal\user\UserInterface $account, $view_mode, $langcode) {
  if (!$account->id() || !\Drupal::currentUser()->hasPermission('administer killbill')) {
    return;
  }
  if (!($killbill_account = Drupal\killbill\KillbillHelpers::retrieveAccount($account))) {
    return;
  }

  $account->content['killbill_account'] = array(
    '#type' => 'user_profile_category',
    '#title' => t('Killbill information'),
    '#weight' => 0,
  );

  if (empty($killbill_account->company)) {
    $account_holder = t('@name', array('@name' => $killbill_account->name));
  }
  else {
    $account_holder = t('@name, @company', array('@name' => $killbill_account->name, '@company' => $killbill_account->company));
  }

  $account->content['killbill_account']['account_holder'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Account holder'),
    '#markup' => $account_holder,
  );

  $account->content['killbill_account']['account_email'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Account e-mail address'),
    '#markup' => \Drupal\Component\Utility\SafeMarkup::checkPlain($killbill_account->email),
  );

  $account->content['killbill_account']['account_currency'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Account currency'),
    '#markup' => \Drupal\Component\Utility\SafeMarkup::checkPlain($killbill_account->currency),
  );

  $account->content['killbill_account']['account_timeZone'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Account time zone'),
    '#markup' => \Drupal\Component\Utility\SafeMarkup::checkPlain($killbill_account->timeZone),
  );

  $account->content['killbill_account']['account_kbid'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Killbill account id'),
    '#markup' => \Drupal\Component\Utility\SafeMarkup::checkPlain($killbill_account->accountId),
  );
}

/**
 * Implements hook_user_insert().
 */
function killbill_user_insert(\Drupal\user\UserInterface $account) {
  Drupal\killbill\KillbillHelpers::createAccount($account);
}
