killbill.settings:
  type: config_entity
  label: Settings
  mapping:
    listener_key:
      type: string
      label: Listener key
    server_url:
      type: string
      label: Server url
    admin_user:
      type: string
      label: Admin (user)
    admin_password:
      type: string
      label: Admin (password)
    api_key:
      type: string
      label: API (key)
    api_secret:
      type: string
      label: API (secret)
