killbill.settings:
  type: mapping
  label: Settings
  mapping:
    listener_key:
      type: string
    push_logging:
      type: boolean
    server_url:
      type: string
    api_user:
      type: string
    api_password:
      type: string
