killbill.settings:
  type: config_entity
  label: Settings
  mapping:
    listener_key:
      type: string
      label: Listener key
    server_url:
      type: string
      label: Server url
    api_user:
      type: string
      label: API (user)
    api_password:
      type: string
      label: API (password)
